version: 0.2

env:
  variables:
    LOG_DIR: logs
    CRUX_VERSION: 19.09-1.5.0-alpha
    AWS_REGION: us-east-1
    AWS_ECR_REPOSITORY_URI: arn:<AWS_PARTITION>:ecr:<AWS_REGION>:<AWS_ACCOUNT_ID>:<ECR_REPOSITORY>

  exported-variables:
    - BUILD_VERSION
    - IMAGE_TAG

phases:
  install:
    commands:
      - BRANCH_NAME=$(echo "${CODEBUILD_SOURCE_VERSION}" | sed 's/refs\/heads\///')
      - UTC_DATE=$(date --utc +%FT%H-%M-%S%Z)
      - COMMIT_HASH=$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | cut -c1-8)
      - BUILD_VERSION=${BRANCH_NAME}-${UTC_DATE}-${COMMIT_HASH}
      - IMAGE_TAG=${BUILD_VERSION:=latest}
      - lein install

  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)

  build:
    commands:
      - lein uberjar
      - docker build --build-arg JAR_FILE=crux-docker-standalone.jar ${AWS_ECR_REPOSITORY_URI}:latest target
      - docker tag ${AWS_ECR_REPOSITORY_URI}:latest ${AWS_ECR_REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - cat '{}' > cloudformation-template-configuration.json
    finally:
      - docker push ${AWS_ECR_REPOSITORY_URI}:latest
      - docker push ${AWS_ECR_REPOSITORY_URI}:${IMAGE_TAG}

artifacts:
  base-directory: target
  files:
    - 'crux-docker-standalone.jar'
  discard-paths: yes
  name: crux-docker-standalone-${BUILD_VERSION}