version: 0.2

env:
  variables:
    LOG_DIR: logs
    CRUX_VERSION: 19.09-1.5.0-alpha
    AWS_REGION: us-east-1
    AWS_ECR_REPOSITORY_URI: arn:<AWS_PARTITION>:ecr:<AWS_REGION>:<AWS_ACCOUNT_ID>:<ECR_REPOSITORY>
    BUILD_VERSION: <BUILD_VERSION>

  exported-variables:
    - BUILD_VERSION
    - IMAGE_TAG

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - BUILD_ENV_NAME="BUILD_ARTIFACT_NAME_${BUILD_ARTIFACT_NAME}"
      - echo "BUILD_ENV_NAME ${BUILD_ENV_NAME}"
      - BUILD_DIRECTORY="${!BUILD_ENV_NAME}"
      - echo "BUILD_DIRECTORY ${BUILD_ENV_NAME}"
      - ls -la
      - echo ${BUILD_VERSION}
      - echo ${BUILD_DIRECTORY}
      - IMAGE_TAG=${BUILD_VERSION:=latest}

  pre_build:
    commands:
      - aws --version
      - $(aws ecr get-login --region ${AWS_REGION} --no-include-email)

  build:
    commands:
      - docker build --build-arg JAR_FILE=crux-docker-standalone.jar ${AWS_ECR_REPOSITORY_URI}:latest "${BUILD_DIRECTORY}"
      - docker tag ${AWS_ECR_REPOSITORY_URI}:latest ${AWS_ECR_REPOSITORY_URI}:${IMAGE_TAG}

  post_build:
    commands:
      - cat '{}' > cloudformation-template-configuration.json
    finally:
      - docker push ${AWS_ECR_REPOSITORY_URI}:latest
      - docker push ${AWS_ECR_REPOSITORY_URI}:${IMAGE_TAG}

artifacts:
  base-directory: target
  files:
    - 'cloudformation-template-configuration.json'
  discard-paths: yes
  name: crux-docker-standalone-${BUILD_VERSION}